# Generated by Django 5.0.4 on 2024-06-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.CharField(blank=True, max_length=256, verbose_name='نام کامنت گذار')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل کامنت گذار')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='وضعیت تایید کامنت')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال کامنت')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='پست مربوطه در وبلاگ')),
            ],
        ),
    ]
