# Generated by Django 5.0.4 on 2024-06-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کتاب')),
                ('author', models.CharField(default='جک لندن', max_length=255, verbose_name='نویسنده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=6, verbose_name='قیمت')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='عکس جلد')),
                ('translator', models.CharField(blank=True, max_length=255, verbose_name='مترجم')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='ناشر')),
                ('year_published', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال انتشار')),
                ('number_of_pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد صفحات کتاب')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد کتاب')),
                ('book_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده کتاب')),
            ],
        ),
    ]
