# Generated by Django 5.0.4 on 2024-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_creator',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recommended',
            field=models.BooleanField(default=True, verbose_name='پیشنهاد می شود'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن نظر'),
        ),
    ]
