# Generated by Django 5.0.4 on 2024-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='پیشنهاد'),
        ),
    ]
