# Generated by Django 5.0.4 on 2024-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nat_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
