BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
XXXXXXX XX XXXXXXXXX
XXXXX XXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXX
XXXXXXX
XXXXXX
BBBBBBBB BBBBBBB
